apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: kubectl-resource
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/bryant-rh/kubectl-resource/releases/download/v0.1.0/kubectl-resource_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./kubectl-resource"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-resource"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/bryant-rh/kubectl-resource/releases/download/v0.1.0/kubectl-resource_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./kubectl-resource"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-resource"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/bryant-rh/kubectl-resource/releases/download/v0.1.0/kubectl-resource_windows_amd64.zip
    sha256: ""
    files:
    - from: "/kubectl-resource.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-resource.exe"
  shortDescription: A new plugin
  homepage: https://github.com/bryant-rh/kubectl-resource
  caveats: |
    Usage:
      $ kubectl kubectl-resource

    For additional options:
      $ kubectl kubectl-resource --help
      or https://github.com/bryant-rh/kubectl-resource/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
